### ISSUE TITLE
File mode specification error: (lsp-timed-out-error)

### ISSUE THREAD

**Issue by ram535** [tigersoldier/lsp-javacomp#2]
I had successfully configure cquery and a dart server with lsp-mode.
I am trying to configure lsp-javacomp but I have been not successful so far.

This is the error I receive when I open a java file after waiting around 6 seconds.
 
**File mode specification error: (lsp-timed-out-error)**

I installed the server with this commands:
```
M-x lsp-javacomp-install-server
M-x lsp-javacomp-update-server
```

This is part of my configuration:

```
     (use-package lsp-mode
       :config
       (require 'lsp-flycheck))

   (use-package lsp-javacomp
   :config
   (setq lsp-javacomp-server-install-dir "~/.emacs.d/javacomp/")
   (add-hook 'java-mode-hook #'lsp-javacomp-enable))

     (use-package company
       :diminish ""
       :bind (:map company-active-map
                   ("C-j" . company-select-next)
                   ("C-k" . company-select-previous))
       :custom
       (company-idle-delay 0.3)
       :config
       (push 'company-capf company-backends)
       (global-company-mode))

     (use-package company-lsp
       :config
       (setq company-lsp-enable-recompletion t)
       (setq company-lsp-async t)
       (setq company-lsp-enable-snippet t)
       (push 'company-lsp company-backends))

```

This is the layout of where I am testing this configuration:
```
.
├── javacomp.json
└── Test.java
```

javacomp.json
```
{
  "logPath": "/tmp/javacomp.log",
  "logLevel": "fine",
}

```

Test.java
```
public class Test {
   public static void main(String[] args) {
      System.out.println("Hello, java");
   }
}

```

**Comment by tigersoldier** [comment]
Can you paste the content of the `*lsp-javacomp*` buffer?

If the buffer doesn't exist, can you paste the content of the `/tmp/javacomp.log` file?

**Comment by ram535** [comment]
**lsp-javacomp stderr** buffer
```
Exception in thread "main" java.lang.NoClassDefFoundError: sun/misc/SharedSecrets
	at org.javacomp.logging.JLogger.findCallerStackTraceElement(JLogger.java:158)
	at org.javacomp.logging.JLogger.log(JLogger.java:148)
	at org.javacomp.logging.JLogger.fine(JLogger.java:140)
	at org.javacomp.server.io.RequestReader.fillBuffer(RequestReader.java:144)
	at org.javacomp.server.io.RequestReader.readLine(RequestReader.java:66)
	at org.javacomp.server.RequestParser.parseHeader(RequestParser.java:58)
	at org.javacomp.server.RequestParser.parse(RequestParser.java:42)
	at org.javacomp.server.RequestDispatcher.dispatchRequest(RequestDispatcher.java:62)
	at org.javacomp.server.JavaComp.run(JavaComp.java:97)
	at org.javacomp.server.JavaComp.main(JavaComp.java:239)
Caused by: java.lang.ClassNotFoundException: sun.misc.SharedSecrets
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:582)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:185)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:496)
	... 10 more

```

**Comment by tigersoldier** [comment]
Hmm, JavaComp doesn't work on Java 9. I filed a bug at tigersoldier/JavaComp#6. Will work on a fix and publish a release.

**Comment by tigersoldier** [comment]
JavaComp v1.1.1 is released with the fix. Please run `M-x lsp-javacomp-update-server` and restart Emacs or re-open all .java files.

BTW, you javacomp.json config is not necessary. `logPath` and `logLevel` are for debugging JavaComp only. Setting `logPath` to `fine` may crash Emacs due to too many content sent to the `*lsp-javacomp*` buffer.

**Comment by ram535** [comment]
Yes, now it is working.
Thanks a lot.
